version: "3.9"

services:
  backend:
    build:
      context: ./src/backend/docker
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/simulation_db
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./src/frontend/docker
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/usr/src/app
    command: yarn start

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simulation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  test-backend:
    build:
      context: ./src/backend/docker
    container_name: test-backend
    volumes:
      - ./src/backend:/app
    depends_on:
      - db
    command: pytest

volumes:
  postgres_data:
