apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - name: backend
          image: backend
          args:
            - sh
            - -c
            - ./wait-for-it.sh db:5432 -- ./wait-for-it.sh redis:6379 -- uvicorn app.main:app --host 0.0.0.0 --port 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@db:5432/simulation_db"
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - mountPath: /app/static
              name: backend-static
      volumes:
        - name: backend-static
          persistentVolumeClaim:
            claimName: backend-static-pvc
      restartPolicy: Always
