name: CI Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy Backend Test Job
        run: |
          kubectl apply -f k8s/deployments/test-backend-job.yaml

      - name: Wait for Job Completion
        run: |
          kubectl wait --for=condition=complete --timeout=300s job/test-backend

      - name: Get Logs
        run: |
          kubectl logs job/test-backend

      - name: Clean up Kubernetes Jobs
        if: always()
        run: |
          kubectl delete job test-backend || true

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy Frontend Test Job
        run: |
          kubectl apply -f k8s/deployments/test-frontend-job.yaml

      - name: Wait for Job Completion
        run: |
          kubectl wait --for=condition=complete --timeout=300s job/test-frontend

      - name: Get Logs
        run: |
          kubectl logs job/test-frontend

      - name: Clean up Kubernetes Jobs
        if: always()
        run: |
          kubectl delete job test-frontend || true
